### ISSUE TITLE
Proposition de toujours afficher les libellés des icônes dans le menu à gauche 

### ISSUE THREAD

**Issue by mbenhamed** [DailyDinities/HubFront#10]
![image](https://cloud.githubusercontent.com/assets/5758758/12486900/f9e7d4b0-c064-11e5-80bd-43fd87c37e24.png)

Je trouve les icônes plus parlantes avec leurs libellées 

![image](https://cloud.githubusercontent.com/assets/5758758/12486910/06efddb0-c065-11e5-87b9-fb92f9fe58cc.png)

**Comment by gsellator** [comment]
J'ai ajouté un tooltip qui apparait au survol de l'icon
