### ISSUE TITLE
Remplacer "Créer une autorisation" par "Créer ou modifier une autorisation" 

### ISSUE THREAD

**Issue by mbenhamed** [DailyDinities/HubFront#12]
En fait, en voulant modifier une autorisation, je n'ai pas trouvé le bouton modifier.. J'ai donc cliqué sur "créer autorisation" . Je me suis aperçu après que l'autorisation en question a été modifiée... ;-)
   
![image](https://cloud.githubusercontent.com/assets/5758758/12679329/e35b06a0-c6a3-11e5-891b-675d9a93b824.png)

![image](https://cloud.githubusercontent.com/assets/5758758/12679315/c87c7c88-c6a3-11e5-8f73-a8ee5dc316fe.png)

**Comment by gsellator** [comment]
Ou permettre de modifier une auth
